{
 "title": "Arun's Tinder Stats",
 "time": {
  "from": null,
  "to": null
 },
 "panels": [
  {
   "title": "Rejected Interests",
   "type": "barchart",
   "gridPos": { "h": 72, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "select interest, count(*) from stats inner join interests using(id) where action=\"dislike\" group by interest;",
     "rawQueryText": "select interest, count(*) from stats inner join interests using(id) where action=\"dislike\" group by interest;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Liked/Disliked/Skipped",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT action, count(*) from stats group by action;\n",
     "rawQueryText": "SELECT action, count(*) from stats group by action;\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Liked",
   "type": "table",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 72 },
   "targets": [
    {
     "queryText": "select * from stats where action = \"like\";",
     "rawQueryText": "select * from stats where action = \"like\";",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Music Artists (liked)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select music_artist, count(*) from stats inner join music_artists using(id) where action = \"like\" group by music_artist;",
     "rawQueryText": "select music_artist, count(*) from stats inner join music_artists using(id) where action = \"like\" group by music_artist;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Music artists (All)",
   "type": "barchart",
   "gridPos": { "h": 114, "w": 9, "x": 0, "y": 86 },
   "targets": [
    {
     "queryText": "select music_artist, count(*) from music_artists group by music_artist;",
     "rawQueryText": "select music_artist, count(*) from music_artists group by music_artist;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}